//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLVTimeSheet.Admin.UserControls {
    
    
    public partial class ucNavitor {
        
        /// <summary>
        /// ucNvparent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration FROM designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ucNvparent;
        
        /// <summary>
        /// ucNvparentLevel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration FROM designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ucNvparentLevel2;
        
        /// <summary>
        /// ucNvaction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration FROM designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ucNvaction;
    }
}
